name: debit
description: A new Flutter application about debit.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  dio: ^1.0.6
  connectivity: ^0.3.1
  # camera: 0.2.9+1
  image_picker: ^0.4.10
  flutter_statusbar: ^0.0.1
  flutter_webview_plugin: ^0.3.0+2

  event_bus:  ^1.0.1
  flutter_redux: ^0.5.3

  json_annotation: ^2.0.0
  path_provider: ^0.4.1
  #permission_handler: 2.1.0
  flutter_spinkit: ^3.1.0
  cached_network_image: ^0.5.1


dev_dependencies:
  build_runner: ^1.1.1
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    # picture
    - assets/images/picture.png
    - assets/images/heart.png
    - assets/images/hearts.png
    - assets/images/googleg_disabled.png
    - assets/images/googleg_standard.png
    - assets/images/avatar_default_login.png
    - assets/images/my_bankCark.png
    - assets/images/my_IDCard.png
    - assets/images/my_personInfo.png
    - assets/images/my_phone.png
    - assets/images/user_borrow.png
    - assets/images/user_exit.png
    - assets/images/user_info.png
    - assets/images/user_password.png
    - assets/images/user_repay.png
    - assets/images/my_basic_camera.png
    - assets/images/my_basic_IDCard_opposite.png
    - assets/images/my_basic_IDCard_positive.png
    - assets/images/other.png
    - assets/images/ic_nav_my_normal.png
    - assets/images/ic_nav_my_pressed.png
    - assets/images/ic_nav_tweet_actived.png
    - assets/images/ic_nav_tweet_normal.png
    - assets/images/ic_nav_discover_actived.png
    - assets/images/ic_nav_discover_normal.png


    # province data
    - assets/data/province.json